server:
  port: 8086

spring:
  application:
    name: NOTIFICATION-SERVICE

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: thakurritika361@gmail.com
    password: oksuegkgrjgjouac
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans