server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: TRACKING-SERVICE

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tracking_db?createDatabaseIfNotExist=true
    username: root
    password: Ritika@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

# ===== SWAGGER =====
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ===== JWT =====
jwt:
  secret: ${JWT_SECRET:ritika_smartcourier_jwt_secure_key_2026_!@#$}
  expiration: 86400000

# ===== EUREKA (FIXED) =====
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# ===== ACTUATOR + ZIPKIN =====
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans